name: "test0001"

on:
  workflow_dispatch:
  
  # schedule:
  #   # 以下の例ではUTC時間で毎日0時に実行されます(例: 0 0 * * *)。
  #   - cron: "40 10 * * *"

jobs:
  run-ls:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run ls command
        # run: ls -al
        run: |
          ls -la
          date


