name: "test0001"

on:
  # workflow_dispatch:
  #   inputs:
  #     name:
  #       description: "Enter your name"
  #       required: true
  #     environment:
  #       description: "Choose environment"
  #       required: true
  #       default: "prod"
  #     release_version:
  #       description: "Release version number"
  #       required: false
  
  schedule:
    # 以下の例ではUTC時間で毎日0時に実行されます(例: 0 0 * * *)。
    - cron: "30 12 * * *"

jobs:
  run-ls:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run ls command
        # run: ls -al
        run: |
          ls -la
          date

      # - name: Show inputs
      #   run: |
      #     echo "Name: ${{ github.event.inputs.name }}"
      #     echo "Environment: ${{ github.event.inputs.environment }}"
      #     echo "Release Version: ${{ github.event.inputs.release_version }}"

